config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :orders do
    resources :payments, only: :new
  end
  resources :drivers, only: [:index, :show]

  resources :materials, only: [:index, :show]
  # resources :materials do
  #   resources :materials, only: [:new]
  # end
  resources :suppliers, only: [:index, :show]
  resources :baskets, only: [:index, :new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  mount StripeEvent::Engine, at: 'https://www.materialised.shop/stripe-webhooks'
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :order
  belongs_to :material
  # has_many :suppliers, through: :materials
  validates :quantity, presence: true
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  before_action :set_basket, only: [:new, :show, :destroy]

  def index
    @order_number = Order.all
    @materials = Material.all
    @basket_items = Basket.all
  end

  def create
    @material = Material.find(params[:material])
    @the_user = current_user
    @basket = Basket.new(basket_params)


    if current_user.order_ids.length < 1
      @order = Order.new
      @order.user = current_user
      @order.state = "pending"
      @order.amount_cents = (@material.price_cents * @basket.quantity) + ((@material.price_cents * @basket.quantity) / 20.to_f)
      @basket.order = @order

      # MUST CHANGE, HARD CODED JUST TO TEST
      @order.supplier_id = 1

      @order.save

      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          price_data: {
            unit_amount: @material.price_cents,
            currency: 'gbp',
            product_data: {
              name: "Total amount:",
            }
          },
          quantity: 1
        }],
        mode: "payment",
        success_url: orders_url,
        cancel_url: order_url(@order)
      )

      @order.update(checkout_session_id: session.id)


    else
      @order_id = current_user.order_ids.first
      @order = Order.find(@order_id)
      @basket.order = @order
      @order.amount_cents = @order.amount_cents + (@material.price_cents * @basket.quantity) + ((@material.price_cents * @basket.quantity) / 20.to_f)
      @order.save

      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        line_items: [{
          price_data: {
            unit_amount: @order.amount_cents,
            currency: 'gbp',
            product_data: {
              name: "Total amount:",
            }
          },
          quantity: 1
        }],
        mode: "payment",
        success_url: orders_url ,
        cancel_url: order_url(@order)
      )

      @order.update(checkout_session_id: session.id)
    end

    @basket.material = @material
    if @basket.save
      # TODO: ADD ALERT / MODAL
    else
      # TODO: ADD ALERT RE UNSUCCESSFUL
    end
  end
  private

  def set_basket
    @basket = Basket.find(params[:id])
  end

  def basket_params
    params.require(:basket).permit(:quantity)
  end

end

app/views/baskets/index.html.erb
<% subtotal = 0 %>
<% @basket_items.each do |item| %>
  <% subtotal += (@materials.find(item.material_id).price * item.quantity) %>
<% end %>



<div class="container">
<div class="w-75 m-auto">
      <h2 class= mt-3> Order Summary</h2>
  <div class="border p-3 mt-3 position-relative w-80 m-auto">
    <div class="m-3">

      <div class="w-50">
        <%= simple_form_for @order_number.first do |f| %>
             <%= f.input :site_location, label: "Delivery address:", label_html: {class: "input-label"},
            input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
            wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
        %>
          <%= f.submit 'Confirm', class: "orange-button mt-2" %>
        <% end %>
      </div>
      <hr class="my-3">

      <%# TODO: add delivery fee algorithm? %>
      <p>Delivery and Handling Fee: £ 17.50</p>
      <% tax_amount = subtotal/20.to_f %>
      <% total = subtotal + tax_amount %>
      <p>Tax = £ <%= sprintf("%.2f", tax_amount) %> </p>
      <h4>Total:  £<%= sprintf("%.2f", total) %></h4>
      <%# <p class="w-50">Notice: one or more of your items is more than 3 metres so a surcharge of £9.99 has been added to the delivery fee</p> %>
    </div>
    <%= link_to "PAY NOW", order_path(@order_number.ids), "class" => "orange-button position-absolute bottom-0 end-0 m-3" %>
  </div>
</div>
<h1 class= my-5>Your Basket</h1>
<div class="w-50 m-auto mb-5">
<div id="index-grid">
    <% @basket_items.each do |item| %>
    <div class="container card-border">
        <div class="container d-flex gap-30 mt-5 pb-5 border-bottom">
            <%= image_tag "#{item.material.image}", class: "img-test" %>

          <div class="name-des">
            <h5><%= @materials.find(item.material_id).name %></h5>
            <p><%= @materials.find(item.material_id).description %></p>
          </div>
        </div>
        <div class="d-flex space-between">
          <div>
          <p class="mt-2">Quantity: <%= item.quantity %></p>
          <p>Vehicle image and type</p>
          </div>
          <div>
            <p class="mt-2">£<%=@materials.find(item.material_id).price.to_i %></p>
            <%= link_to "View details", material_path(item.material_id), class: "btn view-details mb-3" %>
          </div>
        </div>

      </div>
    <% end %>
    </div>
    </div>
  </div>
</div>