config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :orders do
    resources :payments, only: :new
  end
  resources :drivers, only: [:index, :show]

  resources :materials, only: [:index, :show]
  # resources :materials do
  #   resources :materials, only: [:new]
  # end
  resources :suppliers, only: [:index, :show]
  resources :baskets, only: [:index, :new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  mount StripeEvent::Engine, at: 'https://www.materialised.shop/stripe-webhooks'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
    <%= image_tag "Vector.png", class: "logo ms-3" %>
  <div class="text-center text-black p-3" >
    ©2022Copyright
    <a class="text-black" href="#" target="_blank">Materialised.shop</a>
  </div>
  <!-- Copyright -->
  <!-- Section: Social media -->
    <div class="icons my-3">
      <!-- Facebook -->
      <a class="btn text-white btn-floating m-1" style="background-color: #3b5998;" href="https://www.facebook.com/" target="_blank" role="button"><i class="fab fa-facebook-f"></i></a>

      <!-- Twitter -->
      <a class="btn text-white btn-floating m-1" style="background-color: #55acee;" href="https://twitter.com/" target="_blank" role="button"><i class="fab fa-twitter"></i></a>

      <!-- Google -->
      <a class="btn text-white btn-floating m-1" style="background-color: #dd4b39;" href="https://www.google.com/" target="_blank" role="button"><i class="fab fa-google"></i></a>

      <!-- Instagram -->
      <a class="btn text-white btn-floating m-1" style="background-color: #ac2bac;" href="https://www.instagram.com/" target="_blank" role="button"><i class="fab fa-instagram"></i></a>

      <!-- Linkedin -->
      <a class="btn text-white btn-floating m-1" style="background-color: #0082ca;" href="https://www.linkedin.com/" target="_blank" role="button"><i class="fab fa-linkedin-in"></i></a>

    </div>
    <!-- Section: Social media -->
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light nav-background navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="ms-5 mt-2 text-center">
        <%= image_tag ("Vector.png"), class: "logo-width" %>
        <h5 class="logo-color fw-bold mt-1 fs-4">MATERIALISED</h5>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div>

    </div>

    <div class="collapse navbar-collapse me-5" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Products", materials_path, class: "d-inline me-5 nav-link navbar-links-color fw-bold fs-5" %>
          </li>
          <li class="nav-item active me-5 navbar-links-color">
            <i class="fa-solid fa-cart-shopping "></i><%= link_to "Checkout", baskets_path, class: "nav-link d-inline navbar-links-color fw-bold fs-5" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link d-inline navbar-links-color fw-bold fs-5" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link navbar-links-color" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>