config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :orders do
    resources :payments, only: :new
  end
  resources :drivers, only: [:index, :show]

  resources :materials, only: [:index, :show]
  # resources :materials do
  #   resources :materials, only: [:new]
  # end
  resources :suppliers, only: [:index, :show]
  resources :baskets, only: [:index, :new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  mount StripeEvent::Engine, at: 'https://www.materialised.shop/stripe-webhooks'
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :orders, dependent: :destroy
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def show
    @driver = Driver.find(params[:id])
  end
end

app/views/drivers/index.html.erb
<h1>Drivers</h1>

<% @drivers.each do |driver| %>
  <div>
    <h2><%= driver.name %></h2>
    <p><%= driver.email %></p>

    <%= link_to "View driver", driver_path(driver) %>
  </div>
<% end %>

app/views/drivers/show.html.erb
<h1><%= @driver.name %></h1>

<p>Location: <%= @driver.email %></p>
<p>Vehicle Type: <%= @driver.vehicle_type %></p>
<p>Plate Number: <%= @driver.plate_number %></p>
<p>Rating:  <%= @driver.rating %></p>